name: Test workflow
on:
  workflow_dispatch:

jobs:
  send-lark-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.4"

      - name: Run script
        env:
          ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
          MAX_PAPER_NUM: ${{ secrets.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ secrets.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
        run: |
          uv run main.py --debug
